### ISSUE TITLE
Exposing the strobe to ROS

### ISSUE THREAD

**Issue by gellings** [inertialsense/inertial_sense_ros#10]
I'm interested in having a camera provide a strobe to the inertial sense.  Ultimately I'm trying get the inertial sense time stamp of the camera images but I'm planning to start with the a navigation message at each image.

I've been looking through the sdk and the ROS code but I'm getting lost.  Could I get some help exposing the strobe in ROS?

**Comment by superjax** [comment]
I can do this update, but I just need a pointer from @waltjohnson.  When do `DID_STROBE_IN_TIME` messages get published?  Is it just when the strobe in pin on the uINS goes from low to high?  Also, do I need to do any configuration of the communications to enable the strobe messages?

**Comment by gellings** [comment]
I looks like this is working. Thanks for your help with this!
