### ISSUE TITLE
Super Weird TimeStamps when GPS disconnected

### ISSUE THREAD

**Issue by superjax** [inertialsense/inertial_sense_ros#16]

**Comment by waltjohnson** [comment]
Without GPS the time of week fields are just local time since bootup.  Is this what you mean?  We don’t keep a clock when the system is off so we have to wait for GPS to fix the time. 

--
Walt's phone

**Comment by superjax** [comment]
Yeah, something is wrong with the switch.  I've just got to spend a few minutes fixing it.
