### ISSUE TITLE
RPY offset not being applied to imu data

### ISSUE THREAD

**Issue by DevonMorris** [inertialsense/inertial_sense_ros#17]
The quaternion is properly transformed (in an active manner) by the parameter `INS_rpy`. However, the gyroscopic (and probably the accelerometer) data stays in the FRD frame of the INS.

@superjax

**Comment by siddirp** [comment]
@DevonMorris Is this still an issue? If so please let me know what questions you have. If not, could you please close this issue?

**Comment by DevonMorris** [comment]
I'm not sure as I'm not currently using an inertial sense unit. I'll close it and if someone else finds the same issue it can be reopened.
