### ISSUE TITLE
ROS driver does not publish any messages on /gps and /gps/info topics in the compassing branch

### ISSUE THREAD

**Issue by arunanshu-kittyhawk** [inertialsense/inertial_sense_ros#21]
The test config is using a dual GPS uINS with FW version 1.7.2
I see messages being published on all topics except the /gps and /gps/info
This is also true on master branch.
The stream is parameter is set to true for both and the relevant topics are being advertised.
With an older uINS I can see /gps messages but nothing on /gps/info

Could this be an incompatibility with the latest 1.7.2 firmware?

https://github.com/superjax/inertial_sense_ros/issues/10

**Comment by superjax** [comment]
This was an issue with 1.7.2.  I just upgraded the node to 1.7.3 and just tested this on my desk.  It seems to be fixed now on both `master` and `compassing`

**Comment by arunanshu-kittyhawk** [comment]
I'm still seeing the same issue on my system. I'm on the latest compassing branch with v1.7.3 firmware on the uINS. 
Also, is the compassing branch required still or has the compassing feature been merged into master now?

**Comment by arunanshu-kittyhawk** [comment]
Has the most recent commit in the repository worked for you?

**Comment by siddirp** [comment]
@arunanshu-kittyhawk The compassing branch is still required for any compassing applications. Our testing shows both branches functioning properly.

**Comment by siddirp** [comment]
@arunanshu-kittyhawk Is this still an issue? If so please let me know what questions you have. If not, could you please close this issue?
