### ISSUE TITLE
INS ros node publishes NaN.

### ISSUE THREAD

**Issue by BillThePlatypus** [inertialsense/inertial_sense_ros#22]
I did a GPS test outside for a few minutes. When I came in to work with the logged data, I noticed that after a 121 seconds, the position, orientation, and linear twist all start publishing nan. Angular twist still publishes good values.
A bag file, with the ins data as well as ROSFlight data, is [here](https://byu.box.com/s/xl5f6gwq7cfvs0tvd3jdwi5czovx64il).

**Comment by BillThePlatypus** [comment]
I had the gps topic on at the time, and it continued to publish correctly.

**Comment by siddirp** [comment]
@BillThePlatypus Is this still an issue for you? Let me know if you have more questions. If not, can I close this issue?

**Comment by BillThePlatypus** [comment]
It is not currently an issue. It has been a while, so I can't remember details, but this may have been a firmware version issue.
