### ISSUE TITLE
inertialsense_serial_protocol.git repo no longer reachable

### ISSUE THREAD

**Issue by chunhochow** [inertialsense/inertial_sense_ros#25]
The repo https://github.com/inertialsense/inertialsense_serial_protocol.git is no longer reachable? I get a 404 error when I'm trying to clone it. Did you delete or change the permissions on it?

I'm trying to use version 1.6.2 because of issues in #24

**Comment by siddirp** [comment]
Hi @chunhochow,
Do you still need help with this or can we close this issue?

**Comment by chunhochow** [comment]
You can close this. I think I got the newer version to work.
