### ISSUE TITLE
RVIZ visualization

### ISSUE THREAD

**Issue by ghost** [inertialsense/inertial_sense_ros#26]
Hi,

I would like to visualize the ododmetry provided under the /ins topic in the rviz.Can anyone please tell me how i can do that ?

Thanks

**Comment by superjax** [comment]
Hi @chenweng2009,

I don't think we support this out of the box, however, the easiest way would probably be to publish the`\ins` as a tf transform.  I haven't had time to do this yet, however it's not too hard.

http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20broadcaster%20%28C%2B%2B%29

If you end up going down this route, please let me know!  I think this would be useful functionality, but I haven't had time to implement it yet.  

Thanks!
