### ISSUE TITLE
Not getting any output for /gps topic 

### ISSUE THREAD

**Issue by Dinatorehanova** [inertialsense/inertial_sense_ros#27]
Hi,
When i am trying to run the command like "rostopic echo /gps" I am getting the following message
![image](https://user-images.githubusercontent.com/51459647/59971963-1473ed80-9543-11e9-8e89-a1d1d03c7992.png)

But at the same place I can get the gps data using the eval tool in the windows platform.Please help me to resolve this issue.

Is it because I did not update the firmware in the ros for Uins ? When I am trying to update it I am getting this error 

![image](https://user-images.githubusercontent.com/51459647/59971976-3cfbe780-9543-11e9-8031-caa5a809793f.png)

Thank you very much for your valuable time. I will wait for your kind reply.

**Comment by superjax** [comment]
This is probably a ROS environment error.

Have you sourced the `setup.bash` in your `catkin_ws/devel/setup.bash`?

http://wiki.ros.org/catkin/Tutorials/create_a_workspace

**Comment by Dinatorehanova** [comment]
@superjax  I did and all of my  other topics works fine except the /gps topic all my other topics ares working.

I am doing the following


cd myworkspace

source devel/setup.bash

![image](https://user-images.githubusercontent.com/51459647/60056084-f28e7e00-969c-11e9-9aa6-f0b034a64680.png)

And this is coming up

**Comment by superjax** [comment]
could you paste the results of the following?

`rospack profile`
`rospack find inertial_sense`

If the second command fails, could you paste full path to the `inertial_sense` directory?

For reference, this is the report from my machine:
``` bash
$ rospack profile
0.008310   /opt/ros/melodic/share
0.000957   /home/superjax/ws/src
```

``` bash
$ rospack find inertial_sense
/home/superjax/ws/src/inertial_sense_ros
```

I'm primarily checking that the `inertial_sense_ros` workspace is listed under `rospack profile`

**Comment by Dinatorehanova** [comment]
@superjax 
![image](https://user-images.githubusercontent.com/51459647/60078853-02807f00-96ea-11e9-870e-6ed82c30a692.png)

![image](https://user-images.githubusercontent.com/51459647/60078874-0b715080-96ea-11e9-8119-69ac5ec7c7b4.png)

ok I am getting an error with the rospack find inertial sense. My all other topics are working except this /gps.

Please help me with it.

Thank you for your time

**Comment by superjax** [comment]
The reason that `inertial_sense` is not found is that the `myworkspace/setup/devel.bash` is only sourced in the terminal you use to run the node,  therefore, any other terminals don't have the path in their environment.

Try adding `source `/myworkspace/setup/devel.bash` to the bottom of your `~/.bashrc` file.  The `~/.bashrc` file is a script that runs every time you open a new terminal.

For example, here is mine:

``` bash
$ tail ~/.bashrc -n 3
# ROS_WORKSPACE
source /opt/ros/melodic/setup.bash
source ~/ws/devel/setup.bash
```

(The `tail` command just prints out the bottom "n" lines of a file)

**Comment by Dinatorehanova** [comment]
Hi,

Thank you for your kind reply.

If I understand you correcly,

![image](https://user-images.githubusercontent.com/51459647/60113320-bd327080-972e-11e9-8de8-b082d7f5637b.png)

![image](https://user-images.githubusercontent.com/51459647/60113331-c4f21500-972e-11e9-96c1-ce0e84efccc0.png)

Is that ok ?
