### ISSUE TITLE
/IMU topic Orientation remains same

### ISSUE THREAD

**Issue by Dinatorehanova** [inertialsense/inertial_sense_ros#28]
@superjax , is it normal to have a continuous value of 0 under the /imu topic for orientation? It seems the value of my orientation under the /imu topic for (x,y,z,w) does not change at all.Even when my vehicle is moving or tilting it always remains 0 for the orientation part while the other data like linear acceleration and angular velocity changes for each time stamp.

Thanks

**Comment by siddirp** [comment]
@Dinatorehanova That is normal. The /imu topic will publish the IMU data as linear accel and angular velocity. These values are raw IMU data directly from the onboard IMU. Attitude information can be found in the /ins topic under pose/pose/orientation.

**Comment by Dinatorehanova** [comment]
@siddirp , thank you very much for your kind reply. Ok I understand but is it possible that I can retrieve the orientation data in the imu also? If so, can you tell me how I can do that ?

Thanks for your time

**Comment by siddirp** [comment]
@Dinatorehanova  Do you mean you want the INS orientation output to be published as part of the /imu topic? That is probably possible, but you'd need to rewrite some of the node code. If you can give more background I can give you better direction. What is the end goal?

**Comment by Dinatorehanova** [comment]
@siddirp  yes you are correct. I want that the /imu topic will publish the orientation information also.Right now it only gives the linear acceleration and the angular velocity.As /imu topic I need it to publish the orientation information also.Since the /ins is a (navigation/odometry) topic I can not use it for my purpose.

**Comment by siddirp** [comment]
@Dinatorehanova You could rewrite the node to meet your needs. For example, the INS2 callback function could be changed to publish a sensor_msg which seems to be what you need. Or you could track the latest orientation information within the INS2 message and publish it along with the IMU data.

**Comment by Dinatorehanova** [comment]
@siddirp , can you please help me to modify the code? 

I am quite newbie to the ros environment.

**Comment by Dinatorehanova** [comment]
@siddirp  you mean like here 

![image](https://user-images.githubusercontent.com/51459647/60140003-541e1d80-976d-11e9-898d-b85528e78a43.png)

Can you tell me how to write the function ?

**Comment by siddirp** [comment]
This works: ![image](https://user-images.githubusercontent.com/43964540/60197503-bb36e300-97fc-11e9-8aee-db2007c80776.png)

**Comment by Dinatorehanova** [comment]
@siddirp 

Do I need to uncomment the line 376 as well ?

**Comment by siddirp** [comment]
I ran what I showed in the screenshot and it worked well.

**Comment by Dinatorehanova** [comment]
@siddirp ,

Thank you for being patient with me, 
I followed the code that you provided but I do not know still no t getting any change with the orientation data under the /imu topic for each time stamp
![image](https://user-images.githubusercontent.com/51459647/60209804-9fd9d100-9818-11e9-97cc-48e366845639.png)

![image](https://user-images.githubusercontent.com/51459647/60209814-a6684880-9818-11e9-9ea8-5fad6577961c.png)

**Comment by siddirp** [comment]
Is that second image your code? You didn't add anything to it.... Look at the code in the image I sent. Notice how it takes values from the odom_msg and puts them into the imu1_msg.

**Comment by Dinatorehanova** [comment]
@siddirp , sorry for being naive.It works.Thank you very much for your kind co-operation.

Thanks
