### ISSUE TITLE
Conversion from NED frame to ENU frame

### ISSUE THREAD

**Issue by Dinatorehanova** [inertialsense/inertial_sense_ros#29]
Hi @siddirp ,

I am using the robot localization package which looks for ENU frame.But the INS proviedes the /navigation msg in the NED frame. Can you tell me how I can convert the coordinate from NED to ENU ?

And can you please help me with the following queries 

Does the INS automatically remove acceleration due to gravity ? Does the IMU account for the magnetic declination

Thanks 

Dina Torehanova

**Comment by siddirp** [comment]
Hi Dina,
I apologize for not seeing your question earlier. The INS output (the nav solution from EKF) gives the best estimate of attitude and position. If you're asking about the raw IMU data (see DID_DUAL_IMU,  then the answer is no, the acceleration from gravity has not been removed.
Our upcoming release will include updates to the ROS node that will let you select ENU or NED. Until then here is code that shows how to switch between NED or ENU:
```
void InertialSenseROS::INS1_callback(const ins_1_t * const msg)
{
  odom_msg.header.frame_id = frame_id_;
  if (LTCF == NED)
  {
    odom_msg.pose.pose.position.x = msg->ned[0];
    odom_msg.pose.pose.position.y = msg->ned[1];
    odom_msg.pose.pose.position.z = msg->ned[2];
  }
  else if (LTCF == ENU)
  {
    odom_msg.pose.pose.position.x = msg->ned[1];
    odom_msg.pose.pose.position.y = msg->ned[0];
    odom_msg.pose.pose.position.z = -msg->ned[2];
  }

}
```
