### ISSUE TITLE
Coordinate Transformation from Sensor Body Frame to ECEF Frame

### ISSUE THREAD

**Issue by Ashik19** [inertialsense/inertial_sense_ros#32]
Hi,

Can anyone please guide me how I can transfer the coordinate frame of a saved file from sensor body frame to the ECEF frame in ROS platform? My goal is to get the "Rotation matrix from the navigation frame to the global reference frame". I can currently compute the rotation matrix from the quaternion using the Matlab.But I need to transfer the sensor coordinate frame in order to achieve my goal.I have shared my current INS output from rosbag to csv format here.

https://drive.google.com/file/d/1K7hY7ff5bi_ge7hiSUyftOMOF4niFgpM/view?usp=sharing

Any help will be very appreciated.

Thanks

**Comment by siddirp** [comment]
In the top of inertial_sense.cpp include ISPose.h. This is a header file from the InertialSenseSDK:
#"include (custom directory)/SDK/src/ISPose.h"
In inertial_sense.cpp add this code in INS2_callback function:
float vel_ned[3];
quatRot(vel_ned, msg-qn2b, msg->uvw);
