### ISSUE TITLE
Plotting Directional Line

### ISSUE THREAD

**Issue by Chenweng1** [inertialsense/inertial_sense_ros#39]
Hi,

Can anyone please suggest me which tool is appropriate to plot the magnetometer data in order to understand the direction of the vehicle while collecting data using the inertial sense?

Thanks 
Weng

**Comment by siddirp** [comment]
The magnetometer heading is available in DID_INL2_MAG_OBS_IN. You can use
ROS tools to plot it, or record as .csv or something and plot.



*Andrew Priddis | Sr Systems Engineer **|* *Inertial Sense, INC.*

Mobile: (801) 610-6359 | InertialSense.com <http://www.inertialsense.com/>

**Comment by siddirp** [comment]
@
