### ISSUE TITLE
GPS REF LLA

### ISSUE THREAD

**Issue by ethan20120** [inertialsense/inertial_sense_ros#40]
Hi,

Can anyone please tell me whether we need to consider only the 2 decimal for the ref LLA like as given in the github "[40.25, -111.67, 1556.59]". It seems the conversion of ENU position is not matching with the GPS line while using this ref LLA. Any help will be very appreciated.

Thanks
Ethan

**Comment by siddirp** [comment]
https://en.wikipedia.org/wiki/Decimal_degrees
