### ISSUE TITLE
INS only navigation

### ISSUE THREAD

**Issue by Ador2** [inertialsense/inertial_sense_ros#43]
Can I navigate using only the coordinates provided by INS callbacks?

**Comment by siddirp** [comment]
Yes. INS_1 had NED position, LLA position as well as attitude, body
velocity, etc.



*Andrew Priddis | Sr Systems Engineer **|* *Inertial Sense, INC.*

Mobile: (801) 610-6359 | InertialSense.com <http://www.inertialsense.com/>

**Comment by Ador2** [comment]
Thanks a lot, I sent you log files over the email, can you tell me what's wrong, because I moved around over 10 m squared but the ins was moving around 1 to 2 meters.
one last question, how much is the INS error over 60 seconds?

**Comment by siddirp** [comment]
@Ador2 - We resolved this via email so I will close this issue.
