### ISSUE TITLE
ROS message timing

### ISSUE THREAD

**Issue by gellings** [inertialsense/inertial_sense_ros#5]
This might be less of an issue then I think it is but I've notice that the timing of the ROS messages does not seem to be consistent.

I tried streaming the IMU at 200 Hz and recorded the IMU messages.  Below is a screen capture of the visualization of the bag file.

![is_timing](https://user-images.githubusercontent.com/7276826/38152472-41c63f02-3425-11e8-86a3-cde571fb0225.png)

I've noticed in the past that the combination of FTDI chips (for serial to USB conversion) and boost serial libraries for some reason jumble timing possibly because FTDI chip buffer stuff.  Is that what is happening here?

**Comment by jjxtra** [comment]
Are you using boost serial or the Inertial Sense SDK serial?

**Comment by superjax** [comment]
Which branch are you using?

**Comment by superjax** [comment]
Also, I assume those are time stamps from the header and not from the metadata.  Is that right?

**Comment by superjax** [comment]
Both the 'master' and 'release' versions of the ROS node are using the InertialSense sdk serial driver.  FYI

**Comment by gellings** [comment]
I've been using the 'release' branch

**Comment by gellings** [comment]
I'm not sure how rosbags work so maybe showing the screen capture was a bad idea.  It looks like the neither the metadata or the header are constant.

I've noticed that 'seq' always skips one (but sometimes more) and the difference in 'header/nsecs' from one message to the next can be anywhere from 0.001 to 0.015 seconds.

I would send you the bag but I can't get github to attach it.

**Comment by superjax** [comment]
No worries, I have a unit I can test with, and see if I can replicate the behavior.  I assume this was indoors?

I know that the intention was for the header to be stamped from the uINS, so they should be consistent.  I'll get back to you on that.

The "RMC" branch is using an updated streaming method that significantly reduces noise and improves the precision of the IMU time stamping.   I might recommend giving that a try - though you need to update firmware for it to work.  It's what I have been using for my own experiments.

**Comment by superjax** [comment]
Just checked and need to correct myself on that previous post. Precision timing for IMU is currently only available after GPS fix on all branches.

**Comment by gellings** [comment]
I've been testing indoors. I'll try getting a GPS fix and see if that fixes my problem.  

I also can't build 'master'. I get a Error

> No rule to make target 'inertial_sense_ros/CMakeFiles/inertial_sense_node.dir/build'

**Comment by superjax** [comment]
There is a submodule change between release and master, could that be a problem?

**Comment by gellings** [comment]
I did make sure to update my submodule, but thanks for the reminder!

**Comment by gellings** [comment]
Nevermind, blowing away my build and devel folders did it.  Sorry!

**Comment by superjax** [comment]
I just modified the way timestamps are set in `master` it should now use the hardware stamp, translated to local time.

**Comment by gellings** [comment]
Master seems to be working for me.  Thanks for your help with this!
