### ISSUE TITLE
Node crashes with "Call to publish() on an invalid Publisher"

### ISSUE THREAD

**Issue by sethmnielsen** [inertialsense/inertial_sense_ros#7]
The node will sometimes crash at initialization with the following output:
```
[ INFO] [1523401797.717030723]: Connecting to serial port "/dev/rover/ins", at 3000000 baud
[ INFO] [1523401797.717758609]: Connected to uINS on "/dev/rover/ins", at 3000000 baud
[FATAL] [1523401797.723279716]: ASSERTION FAILED
	file = /opt/ros/kinetic/include/ros/publisher.h
	line = 102
	cond = false
	message = 
[FATAL] [1523401797.723353879]: Call to publish() on an invalid Publisher
[FATAL] [1523401797.723369936]: 

[inertial_sense_node-7] process has died [pid 31635, exit code -5, cmd /home/...
```
Simply restarting the node will sometimes fix the problem; but not always. The crash seems to occur unpredictably.

**Comment by superjax** [comment]
Just pushed an update to the `BYU_mars_rover` branch.  Could you see if it fixes it?

**Comment by sethmnielsen** [comment]
The issue appears to be fixed as the inertial_sense_node has yet to crash after initializing it many times.

**Comment by sethmnielsen** [comment]
We're actually having this exact same error again when running the inertial sense node on the Jetson TX2 (Ubuntu 16.04.4, linux kernel version 4.4.38-tegra). On on my laptop (Ubuntu 16.0.4.4, linux kernel version 4.13.0-38-generic), I can't reproduce this error, which is why I thought it was fixed. It launches an indefinite number of times without any errors.

When running it on the TX2, if I run it once, then kill the node, then run it again, it almost always throws this error. It is pretty much random whether it will successfully launch or not with subsequent attempts. I am only running a launch file which launches the inertial sense node with a param file.

**Comment by superjax** [comment]
Okay, I'll see if I can figure it out.

**Comment by superjax** [comment]
A hotfix is to reset the uINS between re-running the node (The button furthest from the SMA connector on the EVB is the reset button)

**Comment by sethmnielsen** [comment]
Great work! It's working flawlessly on the Jetson now. Thanks!
